service: jenkins-test-service

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1

custom:
  dynamodb:
    stages:
      - dev

plugins:
  - serverless-dynamodb-local
  - serverless-offline

functions:
  collectTestResults:
    handler: handler.collectTestResults
    events:
      - http:
          path: collect/{buildId}
          method: get
          request:
            parameters:
              paths:
                buildId: true

resources: # CloudFormation template syntax
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: test_results
        AttributeDefinitions:
          - AttributeName: test_name
            AttributeType: "S"
        KeySchema:
          - AttributeName: test_name
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

package:
  exclude:
    - .env
